name: pixel_field_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  mockito: ^5.4.5

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.2
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/mock_db/
    - assets/img/
    - assets/svgs/
